solve git clone failue/slow problem
Add (如果由于github.com网络连接问题无法下载，可注册登录[码云](https://gitee.com)，先将github代码fork到码云，再直接从码云下载）in line 86.
Users may encounter git cloe failue due to the poor internect connection to github in mainland. An option is to fork the reporsity to gitee.com and to download the code from gitee.com which just takes a few seconds. 

git clone error description:
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed